<?php

define('VERSAO',1); /// VERSAO DO SISTEMA
define('ALFA',""); // SISTEMA ALFA - > define('ALFA',"ALFA");
define('BETA'," BETA"); // SISTEMA BETA - > define('BETA',"BETA");
define('UPGRADE',""); // NUMERO DE UPGRADS 5.x <- ( DEIXAR VAZIO PARA VERSOES BETA E ALFA)
define('ERROS', ""); // NUMERO DE ERROS ARRUMADOS 5.0.x <- ( DEIXAR VAZIO PARA VERSOES BETA E ALFA)
